### Pandas-Dataframe and Series

#### Panda merupakan library data manipulation di python, digunakan untuk data analysis dan data cleaning. Panda menyediakan 2 struktur data yaitu Series dan DataFrame. Series merupakan One Dimension Array-like object, Kalau DataFrame merupakan Two-dimensional, size-mutable.

In [1]:
import pandas as pd

In [3]:
## Series
## Panda Series merupakan 1 Dimensional Array-like object bisa hold berbagai jenis data. mirip column pada sebuah tabel

import pandas as pd
data = [1,2,3,4,5]
series=pd.Series(data)

print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
## Create Series from Dictionary

data = {'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10, 20, 30]
index = ['a','b','c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [22]:
## DataFrame
## Two Dimensional, terdapat rows dan columns, mirip table pada database / excel

## Create a Dataframe from dictionary oof list, Cara pertama
data={
    'Name':['Henry','Jack','Milton'],
    'Age':[25,31,44],
    'City':['Malang','Tokyo','Texas']
}
df=pd.DataFrame(data)   # Create DataFrame berdasarkan variable data
print(df)
print(type(df))

     Name  Age    City
0   Henry   25  Malang
1    Jack   31   Tokyo
2  Milton   44   Texas
<class 'pandas.core.frame.DataFrame'>

In [10]:
## Create DataFrame from list of dictionaries
## Cara kedua

data=[
    {'Name':'Henry','age':22,'City':'Malang'},  # First row
    {'Name':'Darn','age':22,'City':'Malang'},  # Second row
    {'Name':'Lenno','age':22,'City':'Malang'},
    {'Name':'Jack','age':22,'City':'Malang'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  age    City
0  Henry   22  Malang
1   Darn   22  Malang
2  Lenno   22  Malang
3   Jack   22  Malang
<class 'pandas.core.frame.DataFrame'>

In [18]:
## Cara baca file sales_data.csv

df=pd.read_csv('sales_data.csv')
print(df.head(5))

   Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum
2           10003  2024-01-03         Clothing         Levi's 501 Jeans
3           10004  2024-01-04            Books        The Da Vinci Code
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set

   Units Sold  Unit Price  Total Revenue         Region Payment Method
0           2      999.99        1999.98  North America    Credit Card
1           1      499.99         499.99         Europe         PayPal
2           3       69.99         209.97           Asia     Debit Card
3           4       15.99          63.96  North America    Credit Card
4           1       89.99          89.99         Europe         PayPal

In [19]:
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [20]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
data={
    'Name':['Henry','Jack','Milton'],
    'Age':[25,31,44],
    'City':['Malang','Tokyo','Texas']
}

In [24]:
### Accessing data from DataFrame
df

     Name  Age    City
0   Henry   25  Malang
1    Jack   31   Tokyo
2  Milton   44   Texas

In [27]:
## Ambil element name

df['Name']

0     Henry
1      Jack
2    Milton
Name: Name, dtype: object

In [29]:
## Ambil data dari index 0 / row ke 0
df.loc[0]

Name     Henry
Age         25
City    Malang
Name: 0, dtype: object

In [40]:
## Ambil data dari column index
df.iloc[0][0]

C:\Users\Henry\AppData\Local\Temp\ipykernel_21956\1799458538.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Henry'

In [44]:
df

     Name  Age    City
0   Henry   25  Malang
1    Jack   31   Tokyo
2  Milton   44   Texas

In [ ]:
## Accessing a specified element
df.at[1,'Age']  # index 1

np.int64(31)

In [46]:
df.at[2,'Name']

'Milton'

In [49]:
## Accessing specified element using iat
df.iat[2,2]

'Texas'

In [ ]:
### Data Manipulation with DataFrame
df

     Name  Age    City
0   Henry   25  Malang
1    Jack   31   Tokyo
2  Milton   44   Texas

In [51]:
## Add column

df['Salary']=[30000,40000,50000]
df

     Name  Age    City  Salary
0   Henry   25  Malang   30000
1    Jack   31   Tokyo   40000
2  Milton   44   Texas   50000

In [ ]:
## Remove column
df.drop('Salary', axis=1) # hanya temporary bila tidak menggunakan parameter inplace

     Name  Age    City
0   Henry   25  Malang
1    Jack   31   Tokyo
2  Milton   44   Texas

In [ ]:
df # Column salary akan tetap muncul bila memanggil variable df meskipun sudah di drop

     Name  Age    City  Salary
0   Henry   25  Malang   30000
1    Jack   31   Tokyo   40000
2  Milton   44   Texas   50000

In [55]:
df.drop('Salary', axis=1, inplace=True) # Tambahan parameter inplace agar operasi permanen

In [56]:
df

     Name  Age    City
0   Henry   25  Malang
1    Jack   31   Tokyo
2  Milton   44   Texas

In [ ]:
### add age increment to column

df['Age']=df['Age']+1
df

     Name  Age    City
0   Henry   27  Malang
1    Jack   33   Tokyo
2  Milton   46   Texas

In [60]:
## Drop base on row
df.drop(0) # Not permanent

     Name  Age   City
1    Jack   33  Tokyo
2  Milton   46  Texas

In [ ]:
df  # Data index 0 masih ada

     Name  Age    City
0   Henry   27  Malang
1    Jack   33   Tokyo
2  Milton   46   Texas

In [62]:
df.drop(0, inplace=True)    # Permanent Operation dengan parameter inplace

In [63]:
df

     Name  Age   City
1    Jack   33  Tokyo
2  Milton   46  Texas

In [65]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [67]:
# Display data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [68]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000